---
title: "Class Data Files"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    theme: yeti
    toc: TRUE
---

<hr>

### Instructor Data Files

These datasets were compiled or acquired by Dr. Thomley from various sources. More information is provided for some datasets under the  **description** link beside the filename. Click on the dataset name to see the CSV file and get its URL.

    # to read into RStudio using a url
    datasetname <- read.csv("URL HERE") # base code, creates a data frame
    datasetname <- read_csv("URL HERE") # tidyverse, creates a tibble, requires readr package

* [annualinflation.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/annualinflation.csv)
* [anthropometric.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/anthropometric.csv) //
  [description](InstructorDescriptions/anthropometric.html)
* [audiology.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/audiology.csv)
* [balance.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/balance.csv)
* [batterylife.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/batterylife.csv)
* [berkeley.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/berkeley.csv)
* [boonesnowfall.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/boonesnowfall.csv)
* [cereals.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/cereals.csv) //
  [description](InstructorDescriptions/cereals.html)
* [coasters2015.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/coasters2015.csv) //
  [description](InstructorDescriptions/coasters2015.html)
* [couples.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/couples.csv) //
  [description](InstructorDescriptions/couples.html)
* [diamondquality.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/diamondquality.csv) //
  [description](InstructorDescriptions/diamondquality.html)
* [dietcrackers.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/dietcrackers.csv) //
  [description](InstructorDescriptions/dietcrackers.html)
* [egyptianskulls.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/egyptianskulls.csv) //
  [description](InstructorDescriptions/anthropometric.html)
* [electoralvotes.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/electoralvotes.csv)
* [executions.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/executions.csv)
* [farmpop1.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/farmpop1.csv)
* [farmpop2.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/farmpop2.csv)
* [fastfood2017.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/fastfood2017.csv) //
  [description](InstructorDescriptions/fastfood2017.html)
* [florida2000.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/florida2000.csv)
* [gasmileage.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/gasmileage.csv)
* [galtonfamiliesmain.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/galtonfamiliesmain.csv) //
  [description](InstructorDescriptions/galtonheightdata.html)
* [galtonfamiliessub.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/galtonfamiliessub.csv) //
  [description](InstructorDescriptions/galtonheightdata.html)
* [galtonparentheights.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/galtonparentheights.csv) //
  [description](InstructorDescriptions/galtonheightdata.html)
* [happyface.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/happyface.csv)
* [homingpigeons.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/homingpigeons.csv) //
  [description](InstructorDescriptions/homingpigeons.html)
* [lego816.cvs](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/lego816.csv)
* [maunaloaCO2.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/maunaloaCO2.csv)
* [maunaloaCO2annual.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/maunaloaCO2annual.csv)
* [mlb2002.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/mlb2002.csv)
* [mlb2013.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/mlb2013.csv)
* [mmFEB2015.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/mmFEB2015.csv) //
  [description](InstructorDescriptions/mmFEB2015.html)
* [monopolygame.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/monopolygame.csv) //
  [description](InstructorDescriptions/monopoly.html)
* [nccounties20102016.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/nccounties20102016.csv)
* [nccountiesUSR.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/nccountiesUSR.csv)
* [normaltestdata.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/normaltestdata.csv)
* [oldfaithful.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/oldfaithful.csv)
* [oscarages.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/oscarages.csv)
* [pearsonheightdata.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/pearsonheightdata.csv) //
  [description](InstructorDescriptions/pearsonheightdata.html)
* [personalitySTT1810.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/personalitySTT1810.csv)
* [personalitySTT3850.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/personalitySTT3850.csv)
* [popular.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/popular.csv) //
  [description](InstructorDescriptions/popular.html)
* [powerballjackpot.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/powerballjackpot.csv)
* [powerballnumbers.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/powerballnumbers.csv)
* [powerballsets.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/powerballsets.csv)
* [redecorduels.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/redecorduels.csv)
* [redecorranks.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/redecorranks.csv)
* [semmelweisannualbyclinic.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/semmelweisannualbyclinic.csv)
* [semmelweisannualdublin1784.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/semmelweisannualdublin1784.csv)
* [semmelweisannualvienna1784.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/semmelweisannualvienna1784.csv)
* [semmelweismonthly.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/semmelweismonthly.csv)
* [shipsanitation.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/shipsanitation.csv)
* [smallpox.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/smallpox.csv)
* [sunspots.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/sunspots.csv)
* [STT3850majors.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/stt3850majors.csv)
* [titanicCLSE.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/titanicCLSE.csv)
* [titanicCLSU.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/titanicCLSU.csv)
* [titanicSESU.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/titanicSESU.csv)
* [tommypickles1.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/tommypickles1.csv)
* [tommypickles2.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/tommypickles2.csv)
* [unemployment.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/unemployment.csv) //
  [description](InstructorDescriptions/unemployment.html)
* [uscounties2013.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/uscounties2013.csv)
* [usregions.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/usregions.csv)
* [vietnamdraft.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/vietnamdraft.csv) //
  [description](InstructorDescriptions/vietnamdraft.html)
* [wcsweatherdays.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/wcsweatherdays.csv) //
  [description](InstructorDescriptions/wcsweatherdays.html)

### Chihara & Hesterberg 2nd Edition Data Files

These datafiles come from Chihara, L. and Hesterberg, T. (2018). [_Mathematical Statistics with Resampling and R, 2nd Edition_](https://sites.google.com/site/chiharahesterberg/home). New Jersey: John Wiley & Sons. They are also available in the `resampledata` package. More information is provided for some datasets under the  **description** link beside the filename. Click on the dataset name to see the CSV file and get its URL.

    # to read into RStudio using a url
    # then assign dataset to an object
    datasetname <- read.csv("URL HERE") # base code, creates a data frame
    datasetname <- read_csv("URL HERE") # tidyverse, creates a tibble, requires readr package
    
    # to read from resampledata package
    # then assign dataset to an object
    library(resampledata)
    datasetname <- datasetname
    Example: flightdelays <- FlightDelays
    
* [Alelager.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Alelager.csv)
* [Bangladesh.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Bangladesh.csv) //   [description](ChiharaDescriptions/Bangladesh.html)
* [Beerwings.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Beerwings.csv) //
  [description](ChiharaDescriptions/beerwings.html)
* [BookPrices.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/BookPrices.csv)
* [Bushmeat.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Bushmeat.csv)
* [Cereals.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Cereals.csv)
* [Challenger.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Challenger.csv)
* [ChiMarathonMen.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/ChiMarathonMen.csv)
* [Cuckoos.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Cuckoos.csv)
* [Diving2017.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Diving2017.csv)
* [Fatalities.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Fatalities.csv)
* [FishMercury.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/FishMercury.csv)
* [FlightDelays.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/FlightDelays.csv) //
  [description](ChiharaDescriptions/flightdelays.html)
* [Girls2004.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Girls2004.csv)
* [Groceries.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Groceries.csv)
* [GSS2002.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/GSS2002.csv) //
  [description](ChiharaDescriptions/gss2002.html)
* [IceCream.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/IceCream.csv)
* [ILBoys.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/ILBoys.csv)
* [Illiteracy.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Illiteracy.csv)
* [Lottery.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Lottery.csv)
* [MathAnxiety.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/MathAnxiety.csv)
* [Maunaloa.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Maunaloa.csv)
* [MnGroundwater.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/MnGroundwater.csv)
* [MobileAds.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/MobileAds.csv) //
  [description](ChiharaDescriptions/mobileads.html)
* [Nasdaq.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Nasdaq.csv)
* [NBA1617.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/NBA1617.csv)
* [NCBirths2004.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/NCBirths2004.csv) //
  [description](ChiharaDescriptions/ncbirths2004.html)
* [Olympics2012.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Olympics2012.csv)
* [Phillies2009.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Phillies2009.csv)
* [Pitchers2005.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Pitchers2005.csv)
* [Quakes.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Quakes.csv)
* [Quetzal.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Quetzal.csv)
* [RangersTwins2016.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/RangersTwins2016.csv)
* [Reading.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Reading.csv)
* [Recidivism.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Recidivism.csv) //
  [description](ChiharaDescriptions/recidivism.html)
* [Salaries.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Salaries.csv)
* [Service.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Service.csv)
* [SSkateboard.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Skateboard.csv)
* [Skating2010.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Skating2010.csv)
* [Spruce.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Spruce.csv) //
  [description](ChiharaDescriptions/spruce.html)
* [Starcraft.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Starcraft.csv)
* [Titanic.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Titanic.csv)
* [Turbine.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Turbine.csv)
* [TV.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/TV.csv)
* [TXBirths2004.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/TXBirths2004.csv)
* [Verizon.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Verizon.csv) //
  [description](ChiharaDescriptions/verizon.html)
* [Volleyball2009.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Volleyball2009.csv)
* [wafers.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/wafers.csv)
* [Walleye.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Walleye.csv)
* [Watertable.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Chihara/Watertable.csv)

### JB Statistics and Stats 101 Data Files

These datasets were compiled or acquired by Dr. Thomley from Jeremy Balka's [JB Statistics](https://www.youtube.com/user/jbstatistics) and Brandon Foltz's [Stats 101 videos](https://www.youtube.com/c/BrandonFoltz/). More information is provided for some datasets under the  **description** link beside the filename. Click on the dataset name to see the CSV file and get its URL.

    # to read into RStudio using a url
    datasetname <- read.csv("URL HERE") # base code, creates a data frame
    datasetname <- read_csv("URL HERE") # tidyverse, creates a tibble, requires readr package
    
* [jbstatsguineapigs.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/JBStatistics/jbstatsguineapigs.csv)
* [stats101smartphones.csv](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Stats101/stats101smartphones.csv)

***

```{r}
sessionInfo()
```
