---
title: "Oreo Filling Weights Dataset"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: "Updated: `r format(Sys.time(), '%A, %B %d, %Y @ %X')`"
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

```{r setup, include = FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  comment = NA
)
library(readr)
library(dplyr)
```
<hr>

<i class="fas fa-database"></i> [`oreofillingwts.csv`](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/oreofillingwts.csv)

### Description

Weights of the "Oreo creme" filling in a sample of Oreo Original^TM^ and Oreo Double Stuf^TM^ cookies.

### Variables

* type: cookie type (original or double)
* fillgrams: filling weight in grams

```{r}
DATA <- read_csv("https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/oreofillingwts.csv")
glimpse(DATA)
head(DATA)
```

### References

Source: StatCrunch public datasets 

[MIT scientists reveal why it's hard to evenly split Oreo filling between two halves](https://www.engadget.com/mit-oreo-cookie-cream-device-because-science-175016653.html)

<hr>
