---
title: "US Hurricanes 1851-2020 Dataset"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

```{r setup, include = FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE, 
                      echo = FALSE,
                      comment = NA)
library(readr)
library(dplyr)
```
<hr>

<i class="fas fa-database"></i> [`UShurricanes18512020.csv`](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/UShurricanes18512020.csv)

### Description

Data about structures in the United States that are $\ge$ 100 meters tall (as of ~2015).

### Variables

* Year: calendar year
* Named: number of named storms
* Hurricanes: number of hurricanes
* Major: number of major hurricanes (Category 3 and higher)

```{r}
DATA <- read_csv("https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/UShurricanes18512020.csv")
glimpse(DATA)
head(DATA)
```

### References

Source: StatCrunch public datasets 

<hr>

